### ISSUE TITLE
It looks like datafixer stops initialization of OpenVR

### ISSUE THREAD

**Issue by SputerSnoot** [jrbudda/Vivecraft_116#140]
![image](https://user-images.githubusercontent.com/89316631/212737445-3a05dc56-89bf-464d-a267-8b464056b906.png)
```[20:32:20] [main/INFO]: Loading Minecraft 1.19.3 with Fabric Loader 0.14.12
[20:32:20] [main/INFO]: Loading 54 mods:
	- fabric-api 0.72.0+1.19.3
	- fabric-api-base 0.4.20+afca2f3e85 via fabric-api
	- fabric-api-lookup-api-v1 1.6.19+49abcf7e85 via fabric-api
	- fabric-biome-api-v1 12.1.0+b5d379b085 via fabric-api
	- fabric-block-api-v1 1.0.4+e022e5d185 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.29+c6af733c85 via fabric-api
	- fabric-client-tags-api-v1 1.0.11+1134c5b885 via fabric-api
	- fabric-command-api-v1 1.2.21+f71b366f85 via fabric-api
	- fabric-command-api-v2 2.2.0+3fc4752e85 via fabric-api
	- fabric-commands-v0 0.2.38+df3654b385 via fabric-api
	- fabric-containers-v0 0.1.46+df3654b385 via fabric-api
	- fabric-content-registries-v0 3.5.0+1d37d50285 via fabric-api
	- fabric-convention-tags-v1 1.2.1+8e4e694f85 via fabric-api
	- fabric-crash-report-info-v1 0.2.13+aeb40ebe85 via fabric-api
	- fabric-data-generation-api-v1 11.1.4+1134c5b885 via fabric-api
	- fabric-dimensions-v1 2.1.40+48349a3f85 via fabric-api
	- fabric-entity-events-v1 1.5.6+b83334a085 via fabric-api
	- fabric-events-interaction-v0 0.4.39+3baeb27a85 via fabric-api
	- fabric-events-lifecycle-v0 0.2.42+df3654b385 via fabric-api
	- fabric-game-rule-api-v1 1.0.29+99f9db8085 via fabric-api
	- fabric-item-api-v1 2.1.8+1134c5b885 via fabric-api
	- fabric-item-group-api-v1 2.1.11+1134c5b885 via fabric-api
	- fabric-key-binding-api-v1 1.0.30+bc01e09785 via fabric-api
	- fabric-keybindings-v0 0.2.28+df3654b385 via fabric-api
	- fabric-lifecycle-events-v1 2.2.9+23a79c8a85 via fabric-api
	- fabric-loot-api-v2 1.1.19+75e9821185 via fabric-api
	- fabric-loot-tables-v1 1.1.23+9e7660c685 via fabric-api
	- fabric-message-api-v1 5.0.13+6ede1da985 via fabric-api
	- fabric-mining-level-api-v1 2.1.30+49abcf7e85 via fabric-api
	- fabric-models-v0 0.3.26+11ba9c3b85 via fabric-api
	- fabric-networking-api-v1 1.2.16+4017a8cb85 via fabric-api
	- fabric-networking-v0 0.3.33+df3654b385 via fabric-api
	- fabric-object-builder-api-v1 5.3.0+85f102ee85 via fabric-api
	- fabric-particles-v1 1.0.19+f1e4495b85 via fabric-api
	- fabric-recipe-api-v1 1.0.0+5176f73d85 via fabric-api
	- fabric-registry-sync-v0 2.0.4+1134c5b885 via fabric-api
	- fabric-renderer-api-v1 2.2.0+9f179aa185 via fabric-api
	- fabric-renderer-indigo 0.7.0+9f179aa185 via fabric-api
	- fabric-renderer-registries-v1 3.2.29+df3654b385 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.24+afca2f3e85 via fabric-api
	- fabric-rendering-fluids-v1 3.0.17+f1e4495b85 via fabric-api
	- fabric-rendering-v0 1.1.32+df3654b385 via fabric-api
	- fabric-rendering-v1 1.12.0+6dc0edd785 via fabric-api
	- fabric-resource-conditions-api-v1 2.2.2+1134c5b885 via fabric-api
	- fabric-resource-loader-v0 0.10.4+a91e48b785 via fabric-api
	- fabric-screen-api-v1 1.0.40+f1e4495b85 via fabric-api
	- fabric-screen-handler-api-v1 1.3.12+99f9db8085 via fabric-api
	- fabric-sound-api-v1 1.0.7+75e9821185 via fabric-api
	- fabric-transfer-api-v1 2.1.14+ccd377ba85 via fabric-api
	- fabric-transitive-access-wideners-v1 2.3.0+5b9a588b85 via fabric-api
	- fabricloader 0.14.12
	- java 17
	- minecraft 1.19.3
	- vivecraft 1.19.3-0.0.13
[20:32:20] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/D:/Programs/ATLauncher/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[20:32:20] [main/INFO]: Compatibility level set to JAVA_16
[20:32:20] [main/INFO]: Compatibility level set to JAVA_17
[20:32:21] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/SodiumWorldRenderer (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/SodiumWorldRenderer)
[20:32:21] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/gui/SodiumGameOptionPages (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/gui/SodiumGameOptionPages)
[20:32:21] [main/WARN]: Error loading class: net/coderbot/iris/compat/sodium/impl/shader_overrides/IrisChunkProgramOverrides (java.lang.ClassNotFoundException: net/coderbot/iris/compat/sodium/impl/shader_overrides/IrisChunkProgramOverrides)
[20:32:21] [main/WARN]: @Mixin target net.coderbot.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides was not found vivecraft.iris.mixins.json:IrisChunkProgramOverridesMixin from mod vivecraft
[20:32:21] [main/WARN]: Error loading class: net/coderbot/iris/pipeline/HandRenderer (java.lang.ClassNotFoundException: net/coderbot/iris/pipeline/HandRenderer)
[20:32:21] [main/WARN]: Error loading class: net/coderbot/iris/pipeline/newshader/NewWorldRenderingPipeline (java.lang.ClassNotFoundException: net/coderbot/iris/pipeline/newshader/NewWorldRenderingPipeline)
[20:32:21] [main/WARN]: Error loading class: net/coderbot/iris/uniforms/SystemTimeUniforms$FrameCounter (java.lang.ClassNotFoundException: net/coderbot/iris/uniforms/SystemTimeUniforms$FrameCounter)
[20:32:21] [main/WARN]: Error loading class: net/coderbot/iris/uniforms/SystemTimeUniforms$Timer (java.lang.ClassNotFoundException: net/coderbot/iris/uniforms/SystemTimeUniforms$Timer)
[20:32:21] [main/WARN]: Error loading class: net/coderbot/iris/shadow/ShadowMatrices (java.lang.ClassNotFoundException: net/coderbot/iris/shadow/ShadowMatrices)
[20:32:21] [main/WARN]: Error loading class: net/coderbot/iris/shadows/ShadowMatrices (java.lang.ClassNotFoundException: net/coderbot/iris/shadows/ShadowMatrices)
[20:32:21] [main/WARN]: Error loading class: net/coderbot/iris/pipeline/ShadowRenderer (java.lang.ClassNotFoundException: net/coderbot/iris/pipeline/ShadowRenderer)
[20:32:21] [main/WARN]: Error loading class: net/coderbot/iris/pipeline/PipelineManager (java.lang.ClassNotFoundException: net/coderbot/iris/pipeline/PipelineManager)
[20:32:21] [main/WARN]: Error loading class: net/coderbot/iris/gl/program/ProgramUniforms (java.lang.ClassNotFoundException: net/coderbot/iris/gl/program/ProgramUniforms)
[20:32:21] [main/WARN]: Error loading class: me/shedaniel/rei/impl/client/gui/widget/basewidgets/TextFieldWidget (java.lang.ClassNotFoundException: me/shedaniel/rei/impl/client/gui/widget/basewidgets/TextFieldWidget)
[20:32:25] [main/INFO]: Building optimized datafixer
[20:32:30] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:32:31] [Render thread/INFO]: Setting user: OTPOK
[20:32:32] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[20:32:34] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[20:32:55] [Worker-Bootstrap-9/INFO]: 4445 Datafixer optimizations took 29685 milliseconds
[20:34:28] [Render thread/INFO]: [STDERR]: java.lang.RuntimeException: Unknown error (310)
[20:34:28] [Render thread/INFO]: [STDERR]: 	at org.vivecraft.provider.openvr_jna.MCOpenVR.initializeJOpenVR(MCOpenVR.java:909)
[20:34:28] [Render thread/INFO]: [STDERR]: 	at org.vivecraft.provider.openvr_jna.MCOpenVR.init(MCOpenVR.java:261)
[20:34:28] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.redirect$zka000$minecrift(class_310.java:6282)
[20:34:28] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.<init>(class_310.java:544)
[20:34:28] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.method_44604(Main.java:205)
[20:34:28] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:51)
[20:34:28] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[20:34:28] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[20:34:28] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[20:34:29] [Render thread/INFO]: [STDOUT]: Reinit Render: Main Window Changed
[20:34:29] [Render thread/INFO]: Narrator library for x64 successfully loaded
[20:34:29] [Render thread/INFO]: Reloading ResourceManager: vanilla, Fabric Mods (Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric Block API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Client Tags, Fabric Command API (v1), Fabric Command API (v2), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Data Generation API (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Group API (v1), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot API (v2), Fabric Loot Tables (v1), Fabric Message API (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Recipe API (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Sound API (v1), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, Vivecraft)
[20:34:29] [Render thread/INFO]: [STDOUT]: Reinit Render: Window Handle Changed
[20:34:29] [Render thread/INFO]: [STDOUT]: Reinit Render: Mirror Changed
[20:34:30] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[20:34:30] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[20:34:30] [Render thread/INFO]: enabling HRTF: true
[20:34:30] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Speakers (High Definition Audio Device)
[20:34:30] [Render thread/INFO]: Sound engine started
[20:34:30] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[20:34:30] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/signs.png-atlas
[20:34:30] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[20:34:30] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[20:34:30] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[20:34:30] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[20:34:30] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[20:34:31] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[20:34:31] [Render thread/INFO]: [STDOUT]: Reinit Render: Resource Reload
[20:34:31] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[20:34:31] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[20:34:31] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[20:34:34] [Render thread/INFO]: [STDOUT]: Failed to initialise stereo rendering plugin: OpenVR Unknown error (310)
[20:34:38] [Render thread/INFO]: [STDOUT]: Failed to initialise stereo rendering plugin: OpenVR Unknown error (310)
[20:34:41] [Render thread/INFO]: [STDOUT]: Failed to initialise stereo rendering plugin: OpenVR Unknown error (310)
[20:34:44] [Render thread/INFO]: [STDOUT]: Failed to initialise stereo rendering plugin: OpenVR Unknown error (310)
[20:34:48] [Render thread/INFO]: [STDOUT]: Failed to initialise stereo rendering plugin: OpenVR Unknown error (310)
[20:34:50] [Render thread/INFO]: Stopping!
[20:34:50] [Render thread/INFO]: [STDERR]: Unknown error (310)
[20:34:50] [Render thread/INFO]: [STDERR]: 	at org.vivecraft.provider.VRRenderer.setupRenderConfiguration(VRRenderer.java:489)
[20:34:50] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.newRunTick(class_310.java:6487)
[20:34:50] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.handler$zka000$replaceTick(class_310.java:6357)
[20:34:50] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java)
[20:34:50] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_18098(class_310.java:2194)
[20:34:50] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_18096(class_310.java:2164)
[20:34:50] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_18099(class_310.java:2141)
[20:34:50] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1490(class_310.java:1074)
[20:34:50] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.method_44604(Main.java:260)
[20:34:50] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:51)
[20:34:50] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[20:34:50] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[20:34:50] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)```

**Comment by fayer3** [comment]
error 310 means that steamvr had an issue correctly detecting your headset, also you are on the completely wrong github
