### ISSUE TITLE
Cannot build Vivecraft

### ISSUE THREAD

**Issue by sp1ritCS** [jrbudda/Vivecraft_116#25]
I'm unable to build Vivecraft, the install processes works (tho a lot of patches fail), and if I run build.sh it fails.
```
[...]
File: ca.weblite:java-objc-bridge:1.0.0
Skipping due to rules
File: ca.weblite:java-objc-bridge:1.0.0
Skipping due to rules
File Exists: modlauncher-7.0.1.jar
File Exists: launchwrapper-2.1.jar
File Exists: json-20140107.jar
File Exists: asm-all-5.2.jar
File Exists: classgraph-4.8.78.jar
Updating Minecraft.java with Vivecraft version: [Vivecraft 1.16.3 jrbudda-5-1] /home/admin/workspace/games/mc/Vivecraft_116/mcp940/src/minecraft/net/minecraft/client/Minecraft.java
Recompiling...
== MCP 9.40 (data: 9.40, client: 1.16.3, server: 1.16.3) ==
# found wine, ff, ff patches, srgs, name csvs, doc csvs, param csvs, astyle, astyle config, scalac, rg, ss
== Recompiling client ==
> Cleaning bin
> Recompiling
'"scalac" -encoding UTF-8 -target:jvm-1.8 -classpath "jars/versions/1.16.3/1.16.3.jar:lib:lib/*:jars/libraries/com/google/code/findbugs/jsr305/3.0.1/jsr305-3.0.1.jar:jars/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:jars/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar:jars/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar:jars/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:jars/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar:jars/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:jars/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:jars/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar:jars/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar:jars/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar:jars/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar:jars/libraries/com/google/guava/guava/21.0/guava-21.0.jar:jars/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar:jars/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar:jars/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:jars/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar:jars/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-linux.jar:jars/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-linux.jar:jars/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar:jars/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar:jars/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar:jars/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar:jars/libraries/org/json/json/20140107/json-20140107.jar:jars/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-linux.jar:jars/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:jars/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar:jars/libraries/com/mojang/patchy/1.1/patchy-1.1.jar:jars/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar:jars/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-linux.jar:jars/libraries/cpw/mods/modlauncher/7.0.1/modlauncher-7.0.1.jar:jars/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-linux.jar:jars/libraries/io/github/classgraph/classgraph/4.8.78/classgraph-4.8.78.jar:jars/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar:jars/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar:jars/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-linux.jar:jars/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar:jars/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar:jars/libraries/com/mojang/authlib/1.6.25/authlib-1.6.25.jar:jars/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar:jars/libraries/net/minecraft/launchwrapper/2.1/launchwrapper-2.1.jar:jars/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar:jars/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-linux.jar:jars/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar:jars/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-linux.jar:jars/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar:jars/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar" -sourcepath src/minecraft -d bin/minecraft @temp/java_src_client.txt @temp/scala_src_client.txt' failed : 1

== ERRORS FOUND in SCALA CODE ==

error: java.lang.NoClassDefFoundError: javax/tools/ToolProvider
	at scala.reflect.io.JavaToolsPlatformArchive.iterator(ZipArchive.scala:242)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.reflect.io.AbstractFile.foreach(AbstractFile.scala:92)
	at scala.tools.nsc.util.DirectoryClassPath.traverse(ClassPath.scala:308)
	at scala.tools.nsc.util.DirectoryClassPath.x$16$lzycompute(ClassPath.scala:317)
	at scala.tools.nsc.util.DirectoryClassPath.x$16(ClassPath.scala:317)
	at scala.tools.nsc.util.DirectoryClassPath.packages$lzycompute(ClassPath.scala:317)
	at scala.tools.nsc.util.DirectoryClassPath.packages(ClassPath.scala:317)
	at scala.tools.nsc.util.DirectoryClassPath.packages(ClassPath.scala:297)
	at scala.tools.nsc.util.MergedClassPath$$anonfun$packages$1.apply(ClassPath.scala:375)
	at scala.tools.nsc.util.MergedClassPath$$anonfun$packages$1.apply(ClassPath.scala:375)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.tools.nsc.util.MergedClassPath.packages$lzycompute(ClassPath.scala:375)
	at scala.tools.nsc.util.MergedClassPath.packages(ClassPath.scala:370)
	at scala.tools.nsc.symtab.SymbolLoaders$PackageLoader.doComplete(SymbolLoaders.scala:243)
	at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:194)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1231)
	at scala.reflect.internal.Mirrors$RootsBase.init(Mirrors.scala:240)
	at scala.tools.nsc.Global.rootMirror$lzycompute(Global.scala:59)
	at scala.tools.nsc.Global.rootMirror(Global.scala:57)
	at scala.tools.nsc.Global.rootMirror(Global.scala:37)
	at scala.reflect.internal.Definitions$DefinitionsClass.<init>(Definitions.scala:166)
	at scala.reflect.internal.Definitions$definitions$.<init>(Definitions.scala:20)
	at scala.reflect.internal.SymbolTable.definitions$lzycompute(SymbolTable.scala:13)
	at scala.reflect.internal.SymbolTable.definitions(SymbolTable.scala:13)
	at scala.tools.nsc.Global$Run.<init>(Global.scala:1290)
	at scala.tools.nsc.Driver.doCompile(Driver.scala:32)
	at scala.tools.nsc.Main$.doCompile(Main.scala:79)
	at scala.tools.nsc.Driver.process(Driver.scala:54)
	at scala.tools.nsc.Driver.main(Driver.scala:67)
	at scala.tools.nsc.Main.main(Main.scala)
Exception in thread "main" java.lang.NoClassDefFoundError: javax/tools/ToolProvider
	at scala.reflect.io.JavaToolsPlatformArchive.iterator(ZipArchive.scala:242)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.reflect.io.AbstractFile.foreach(AbstractFile.scala:92)
	at scala.tools.nsc.util.DirectoryClassPath.traverse(ClassPath.scala:308)
	at scala.tools.nsc.util.DirectoryClassPath.x$16$lzycompute(ClassPath.scala:317)
	at scala.tools.nsc.util.DirectoryClassPath.x$16(ClassPath.scala:317)
	at scala.tools.nsc.util.DirectoryClassPath.packages$lzycompute(ClassPath.scala:317)
	at scala.tools.nsc.util.DirectoryClassPath.packages(ClassPath.scala:317)
	at scala.tools.nsc.util.DirectoryClassPath.packages(ClassPath.scala:297)
	at scala.tools.nsc.util.MergedClassPath$$anonfun$packages$1.apply(ClassPath.scala:375)
	at scala.tools.nsc.util.MergedClassPath$$anonfun$packages$1.apply(ClassPath.scala:375)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.tools.nsc.util.MergedClassPath.packages$lzycompute(ClassPath.scala:375)
	at scala.tools.nsc.util.MergedClassPath.packages(ClassPath.scala:370)
	at scala.tools.nsc.symtab.SymbolLoaders$PackageLoader.doComplete(SymbolLoaders.scala:243)
	at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:194)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1231)
	at scala.reflect.internal.Mirrors$RootsBase.init(Mirrors.scala:240)
	at scala.tools.nsc.Global.rootMirror$lzycompute(Global.scala:59)
	at scala.tools.nsc.Global.rootMirror(Global.scala:57)
	at scala.tools.nsc.Global.rootMirror(Global.scala:37)
	at scala.reflect.internal.Definitions$DefinitionsClass.<init>(Definitions.scala:166)
	at scala.reflect.internal.Definitions$definitions$.<init>(Definitions.scala:20)
	at scala.reflect.internal.SymbolTable.definitions$lzycompute(SymbolTable.scala:13)
	at scala.reflect.internal.SymbolTable.definitions(SymbolTable.scala:13)
	at scala.tools.nsc.Global$Run.<init>(Global.scala:1290)
	at scala.tools.nsc.Driver.doCompile(Driver.scala:32)
	at scala.tools.nsc.Main$.doCompile(Main.scala:79)
	at scala.tools.nsc.Driver.process(Driver.scala:54)
	at scala.tools.nsc.Driver.main(Driver.scala:67)
	at scala.tools.nsc.Main.main(Main.scala)
================================

Traceback (most recent call last):
  File "build.py", line 316, in <module>
    main(os.path.abspath(mcp_version))	
  File "build.py", line 278, in main
    recompile_side( commands, CLIENT)
  File "/home/admin/workspace/games/mc/Vivecraft_116/mcp940/runtime/mcp.py", line 143, in recompile_side
    commands.recompile(side)
  File "/home/admin/workspace/games/mc/Vivecraft_116/mcp940/runtime/commands.py", line 1628, in recompile
    self.runcmd(forkcmd, log_file=pathlog[side])
  File "/home/admin/workspace/games/mc/Vivecraft_116/mcp940/runtime/commands.py", line 1697, in runcmd
    raise CalledProcessError(process.returncode, forkcmd, output)
runtime.commands.CalledProcessError: Command '"scalac" -encoding UTF-8 -target:jvm-1.8 -classpath "jars/versions/1.16.3/1.16.3.jar:lib:lib/*:jars/libraries/com/google/code/findbugs/jsr305/3.0.1/jsr305-3.0.1.jar:jars/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:jars/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar:jars/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar:jars/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:jars/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar:jars/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:jars/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:jars/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar:jars/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar:jars/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar:jars/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar:jars/libraries/com/google/guava/guava/21.0/guava-21.0.jar:jars/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar:jars/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar:jars/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:jars/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar:jars/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-linux.jar:jars/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-linux.jar:jars/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar:jars/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar:jars/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar:jars/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar:jars/libraries/org/json/json/20140107/json-20140107.jar:jars/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-linux.jar:jars/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:jars/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar:jars/libraries/com/mojang/patchy/1.1/patchy-1.1.jar:jars/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar:jars/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-linux.jar:jars/libraries/cpw/mods/modlauncher/7.0.1/modlauncher-7.0.1.jar:jars/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-linux.jar:jars/libraries/io/github/classgraph/classgraph/4.8.78/classgraph-4.8.78.jar:jars/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar:jars/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar:jars/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-linux.jar:jars/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar:jars/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar:jars/libraries/com/mojang/authlib/1.6.25/authlib-1.6.25.jar:jars/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar:jars/libraries/net/minecraft/launchwrapper/2.1/launchwrapper-2.1.jar:jars/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar:jars/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-linux.jar:jars/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar:jars/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-linux.jar:jars/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar:jars/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar" -sourcepath src/minecraft -d bin/minecraft @temp/java_src_client.txt @temp/scala_src_client.txt' returned non-zero exit status 1
```

Could you provide a Dockerfile that builds a container with the correct toolchain so that it builds?

**Comment by Techjar** [comment]
Wut. Why is it trying to use scala? Also if you're just wanting to play, get the installer from the releases page.

**Comment by sp1ritCS** [comment]
You only release PE binaries on the releases page.

**Comment by Techjar** [comment]
They are just jars wrapped in a launcher, rename it to .jar if you're trying to install on non-Windows.

**Comment by ElijahZAwesome** [comment]
im also having scala errors on windows

**Comment by Techjar** [comment]
I'm not sure why you're getting those errors as we don't even use Scala, but I guess you need to run the decompile with JDK 8 specifically, due to JDK 9+ breaking compatibility.
