### ISSUE TITLE
1.16.4 Vivecraft + Forge Crashes

### ISSUE THREAD

**Issue by fenpaws** [jrbudda/Vivecraft_116#34]
I tried out Vivecraft with forge, `35.0.7 `and `35.1.0`, both versions just resulted in a crash.

I use MultiMC to launch MC, but MultiMC doesn't seem to be the issue since normal Vivecraft works just fine.

I run Java 8 Update 241

```java
Failed to find Minecraft main class:
java.lang.ClassNotFoundException: io.github.zekerzhayard.forgewrapper.installer.Main
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:171)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by jrbudda** [comment]
run the instance once after you install forge, but before you install vivecraft

**Comment by fenpaws** [comment]
Yeah after that it works, I thought the installer itself would download forge and install it.
Thanks for the quick help!
